log: true
uid: www-data
gid: www-data
cookie_domain: localhost
dir: /var/www/html/web
data_dir: /var/www/data
tmp_dir: /var/www/data/tmp
secret: 6gLT2M7MMbsrok3bihzg8W7zakWkFjA9huUZBWKf24aqmxicdO31IZk5pKWzZDf7QZMXbFpHuGm8Z1wpPONN8dsDr20iLL4Gcp17aDfZPs9uOs5ff9dgMHz2ntxw4T3B
salt: 6gLT2M7
title: eDy

daemon:
  threads: 4
  lock_time: 10

databases:
  default: Diary
  Diary:
    host: host.docker.internal
    username: root
    password:
    log: mysql
    slow_log_time: 150

memcache:
  host: memcached
  port: 11211

session:
  name: eDiary
  expire: 604800


user:
  password:
    min: 8
    max: 72

data:
  assignment_file: /var/www/data/assignments/files